### ISSUE TITLE
Setup travis CI for automatic testing

### ISSUE THREAD

**Issue by gabriel-araujjo** [cadubentzen/ginga-rs#1]
Hooking the repository with travis allows automatic checks before each merge.

**Comment by cadubentzen** [comment]
Added a Travis CI. A few questions:

- Add [rustfmt](https://github.com/rust-lang-nursery/rustfmt) for travis CI to check?
- Should we use Rust nightly toolchain to keep up with newest standards/features?

I can add changes it in #2 to address the points above upon answer.

**Comment by cadubentzen** [comment]
As discussed personally with @gabriel-araujjo, he agreed to use nightly features and enforce coding style with rustfmt. So I added a new commit doing just this in #2.
